kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chatbot-va-oct2-3-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: chatbot-va-oct2-3-dsp-job
    namespace: chatbot-va-oct2-3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chatbot-va-oct2-3-dsp-job-role